ci: 更新 Aliyun 镜像构建和推送流程
-替换原有的资源文件读取方式，使用固定 URL 克隆仓库
- 添加错误处理和状态检查，提高流程的健壮性- 增加对 Rust项目的检测和处理
- 优化 Docker 镜像构建和推送流程，包括登录、打标签和推送步骤

diff --git a/.github/workflows/docker.yaml b/.github/workflows/docker.yaml
--- a/.github/workflows/docker.yaml
+++ b/.github/workflows/docker.yaml
@@ -184,8 +184,43 @@ jobs:
     - name: Build and push image Aliyun
       if: ${{env.git_repo == 'true' }}
       run: |
-        while IFS= read -r line || [ -n "$line" ]; do
-          echo "$line"
-          git clone $line
-          ls -alH
-        done < resources.txt
+        TOKEN="6b42d6ab6ba264324fee43f626d0a700"
+        REPO_URL="https://gitee.com/archknight/ls-license-test.git"
+        CLONE_URL="https://oauth2:${TOKEN}@gitee.com/archknight/ls-license-test.git"
+        LOCAL_DIR="ls-license-test"
+        git clone $CLONE_URL $LOCAL_DIR
+        if [ $? -eq 0 ]; then
+            echo "Repository cloned successfully."
+        else
+            echo "Failed to clone repository."
+            exit 1
+        fi
+        cd $LOCAL_DIR
+        if [ -f "Cargo.toml" ]; then
+            echo "This is a Rust project."
+
+            image_name_tag="jetbrains-go:v1.0.0"
+            docker build -t $image_name_tag .
+
+            if [ $? -eq 0 ]; then
+                echo "Docker image built successfully."
+
+                docker login -u $ALIYUN_REGISTRY_USER -p $ALIYUN_REGISTRY_PASSWORD $ALIYUN_REGISTRY
+                new_image="$ALIYUN_REGISTRY/$ALIYUN_NAME_SPACE/$image_name_tag"
+                docker tag $image_name_tag $new_image
+                docker push $new_image
+
+                if [ $? -eq 0 ]; then
+                    echo "Docker image pushed to Aliyun successfully."
+                else
+                    echo "Failed to push Docker image to Aliyun."
+                    exit 1
+                fi
+            else
+                echo "Failed to build Docker image."
+                exit 1
+            fi
+        else
+            echo "This is not a Rust project."
+            exit 1
+        fi
